resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend
        annotations:
          external-dns.alpha.kubernetes.io/hostname: store-dev.automateit.ca.