apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend
        annotations:
          external-dns.alpha.kubernetes.io/hostname: store.automateit.ca